export const PAGE_LOADING = "PAGE_LOADING";
export const CURSOR_TYPE = "CURSOR_TYPE";
export const MOUSE_ENTERED = "MOUSE_ENTERED";
export const PAGE_LOADING_CONTENT = "PAGE_LOADING_CONTENT";
export const INITIAL_PAGE_LOADING = "INITIAL_PAGE_LOADING";
export const CURSOR_IMAGE = "CURSOR_IMAGE";